title: Seven Databases in Seven Weeks
author: Luc Perkins, Eric Redmond, and Jim Wilson
theme: vex-hugo
watch: true
params:
  meta:
  - name: og:title
    content: Seven Databases in Seven Weeks
  - name: og:description
    content: "Seven Databases in Seven Weeks: A Guide to Modern Databases and the NoSQL Movement"
  - name: og:image
    content: https://7dbs.io/img/sevendbs.jpg
  - name: og:url
    content: https://7dbs.io
  description: A Guide to Modern Databases and the NoSQL Movement
  navbar:
    menu:
    - link: "#testimonials"
      text: Testimonials
  testimonials:
    title: Testimonials
    blocks:
    - text: Look, if you're building a new app or company, getting the database right is a big deal. Moving data stores is a hassle that many people take too lightly only to learn the hard way that they should have been more thorough. Knowing what to avoid, what mistakes people make, the problem set that these items are suited to and what they aren't suited to, all the while making sure you know what is there for you now, makes this book another winner every bit as good as the last edition, if not better.
      name: William Ryan
      position: Amazon reviewer
    - text: Not sure which database you need? This book gives you an awesome primer on each one that includes getting setup, differentiating features, and some hands on examples. I highly recommend this to anyone that wants a primer on the various databases that are out there.
      name: Nick Capito
      position: Amazon reviewer
    - text: Choosing a database is perhaps one of the most important architectural decisions a developer can make. *Seven Databases in Seven Weeks* provides a fantastic tour of different technologies and makes it easy to add each to your engineering toolbox.
      name: Dave Parfitt
      position: Senior Site Reliability Engineer, Mozilla
  header:
    title: Seven Databases in Seven Weeks
    subtitle: A Guide to Modern Databases and the NoSQL Movement
    text: A hands-on guide to PostgreSQL, HBase, MongoDB, CouchDB, DynamoDB, Neo4j, and Redis. Co-authored by [Luc Perkins](https://github.com/lucperkins), [Eric Redmond](https://github.com/coderoshi), and [Jim Wilson](https://github.com/jimbojw).
    buttons:
    - link: https://www.amazon.com/Seven-Databases-Weeks-Modern-Movement/dp/1680502530
      text: Amazon
      class: amazon
    - link: https://pragprog.com/book/pwrdata/seven-databases-in-seven-weeks-second-edition
      text: PragProg
      class: pragprog
    - link: http://www.powells.com/book/-9781680502534
      text: Powell's
      class: powells
    image:
      path: /img/sevendbs.jpg
  databases:
  - name: PostgreSQL
