[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_BASEURL = "https://7dbs.io"
HUGO_VERSION = "0.43-DEV-0EFD3748"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.44"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.44"
