[build]
publish = "public"
command = "hugo"
functions = "functions"

[context.production.environment]
HUGO_BASEURL = "https://7dbs.io"
HUGO_VERSION = "0.46"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"
